# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-10 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyblogInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'myblog_infos',
                'managed': False,
            },
        ),
    ]
